ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS client_type VARCHAR(20) NOT NULL DEFAULT 'person',
  ADD COLUMN IF NOT EXISTS document_id VARCHAR(30),
  ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(30),
  ADD COLUMN IF NOT EXISTS contact_name VARCHAR(120);
